### ISSUE TITLE
Cant run using docker image

### ISSUE THREAD

**Issue by lcnerd** [marcosfermin/pencilcrunch#7]
Hi cant seem to run through docker. everything seems to work fine but when i try to connect it keeps giving me a 500 Internal Server error.

> **Internal Server Error**
The server encountered an internal error or misconfiguration and was unable to complete your request. Please contact the server administrator at [no address given] to inform them of the time this error occurred, and the actions you performed just before this error. 
More information about this error may be available in the server error log.

this is the containers .log file

> {"log":"AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message\n","stream":"stderr","time":"2017-04-28T14:15:49.114135118Z"}
{"log":"Starting web server: apache2.\n","stream":"stdout","time":"2017-04-28T14:15:50.138870067Z"}
{"log":"Starting MySQL database server: mysqld ..\n","stream":"stdout","time":"2017-04-28T14:15:52.291578949Z"}
{"log":"Checking for tables which need an upgrade, are corrupt or were \n","stream":"stdout","time":"2017-04-28T14:15:52.296441591Z"}
{"log":"not closed cleanly..\n","stream":"stdout","time":"2017-04-28T14:15:52.29649838Z"}

**Comment by psanders** [comment]
Thanks for reporting the issue. I'm looking into this.

**Comment by Eduardoveras94** [comment]
Having the same issue here, everything installs correctly but i get 500 internal server error when trying to enter the website

**Comment by jblandino** [comment]
Hey @psanders  and @lcnerd 

Thank you for this issue, this error is due to the connection of the database, in the file run.sh is looking for this specific lines 
 ````bash
sed -i "s/'hostname' => '',/'hostname' => '$DB_HOSTNAME',/" /var/www/html/application/config/database.php
sed -i "s/'database' => '',/'database' => '$DB_NAME',/" /var/www/html/application/config/database.php
sed -i "s/'username' => '',/'username' => '$DB_NAME',/" /var/www/html/application/config/database.php
sed -i "s/'password' => '',/'password' => '$DB_PASSWORD',/" /var/www/html/application/config/database.php
sed -i "s/= 'install';/= 'login';/" /var/www/html/application/config/routes.php
````
> https://github.com/marcosfermin/pencilcrunch/blob/master/etc/build/run.sh#L11-L15


And the database file has credentials like "root" (which are the ones specific to my machine).

The error was mine when uploading that file, I will commit in a few minutes to fix this error.

> __Note:__ Check the database file here [database.php](https://github.com/marcosfermin/pencilcrunch/blob/master/application/config/database.php#L67-L70)

**Comment by jblandino** [comment]
@psanders, @Eduardoveras94 and @lcnerd

Hey guys, please check the merge I just made with the problem solution... 

> Check this [Merge #8 ](https://github.com/marcosfermin/pencilcrunch/pull/8)

**Comment by psanders** [comment]
I just re-build the image and can confirm that it works(so I'm closing this issue). Also, to avoid this in the future I've created a repository on Docker Hub where we can keep a docker image base on a release.

**Comment by jblandino** [comment]
Perfect, paste the Docker Hub repository please.
